@extends('layouts.app-home')

@section('content')

<!-- Menu Sidebar Section Start -->
<div class="menu-sidebar-area">
    <div class="menu-sidebar-wrapper">
        <div class="menu-sidebar-close">
            <button class="menu-sidebar-close-btn" id="menu_sidebar_close_btn">
                <i class="fal fa-times"></i>
            </button>
        </div>
        <div class="menu-sidebar-content">
            <div class="menu-sidebar-logo">
                <a href="index.php"><img src="assets/images/task-img/Task-365-Logo.png" alt="logo" /></a>
            </div>
            <div class="mobile-nav-menu"></div>
            <div class="menu-sidebar-content">
                <div class="menu-sidebar-single-widget">
                    <h5 class="menu-sidebar-title">Privacy policy</h5>
                    <div class="header-contact-info">
                        <span><i class="fa-solid fa-location-dot"></i>20, Bordeshi, New York, US</span>
                        <span><a href="mailto:hello@transico.com"><i
                                    class="fa-solid fa-envelope"></i>task365.in@gmail.com</a> </span>
                        <span><a href="tel:+123-456-7890"><i class="fa-solid fa-phone"></i>+123-456-7890</a></span>
                    </div>
                    <div class="social-profile">
                        <a href="javasceipt:void(0);"><i class="fa-brands fa-facebook-f"></i></a>
                        <a href="javasceipt:void(0);"><i class="fa-brands fa-twitter"></i></a>
                        <a href="javasceipt:void(0);"><i class="fa-brands fa-linkedin-in"></i></a>
                        <a href="javasceipt:void(0);"><i class="fa-brands fa-youtube"></i></a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<!-- Menu Sidebar Section Start -->
<div class="body-overlay"></div>

@include('common.login-form')

<!-- Page Header Start !-->
<div class="page-breadcrumb-area page-bg">
    <!-- <div class="page-overlay"></div> -->
    <div class="container">
        
    
    <h3 class="mb-4 text-center">Terms and Conditions</h3>
    <p><strong>Last Updated:</strong> 7th Feb 2025</p>
    <hr>

    <h5>1. Introduction</h5>
    <p>This document is an electronic record under the provisions of the Information Technology Act, 2000 and Rules framed thereunder. It is generated by a computer system and does not require physical or digital signatures. <strong>www.task365.in</strong> ("Platform") is owned and operated by <strong>Lorhan Spot Earn Pvt Ltd</strong> ("Task365"), with its registered office at Flat No. 07/3, Second Floor, 18th Main Jaya Nagar, 9th Block Bangalore, Karnataka – 560041 India.</p>
    <p>By accessing or using Task365.in, its mobile apps, or related services (collectively, "Services"), you agree to comply with these Terms and Conditions ("Terms"), along with our Privacy Policy, IPR Policy, and other referenced documents. Continued use signifies acceptance of any future revisions.</p>

    <h5>2. Definitions</h5>
    <ul>
      <li><strong>"User" or "You":</strong> Any natural/legal person accessing or using the Platform.</li>
      <li><strong>"Service Provider":</strong> Businesses/individuals listed on www.task365.in offering services.</li>
      <li><strong>"Content":</strong> Text, graphics, trademarks, reviews, and other materials on the Platform.</li>
      <li><strong>"UVN/BVN":</strong> Virtual numbers used for communication between Users and Service Providers.</li>
    </ul>

    <h5>3. Eligibility & Registration</h5>
    <ul>
      <li>Users must be 18+ years old and legally capable of entering binding contracts.</li>
      <li>Provide accurate information during registration. False details may result in account suspension.</li>
      <li>Maintain confidentiality of login credentials. Task365 is not liable for unauthorized account access.</li>
    </ul>

    <h5>4. Services Overview</h5>
    <p>Task365 facilitates connections between Users and Service Providers for local needs (e.g., home services, repairs, tutoring).</p>
    <ul>
      <li><strong>Listings:</strong> Service Providers are responsible for their listings' accuracy. Task365 does not endorse or guarantee service quality.</li>
      <li><strong>Leads:</strong> Task365 may share User contact details with Service Providers for service fulfillment.</li>
      <li><strong>Payments:</strong> Transactions may be processed via third-party gateways. Task365 acts as a facilitator, not a party to transactions.</li>
    </ul>

    <h5>5. User Responsibilities</h5>
    <ul>
      <li>Use the Platform lawfully. Do not post offensive, fraudulent, or infringing content.</li>
      <li>Verify Service Provider credentials independently. Task365 does not pre-screen listings.</li>
      <li>Communicate respectfully. Harassment, spam, or misuse of communication tools is prohibited.</li>
    </ul>

    <h5>6. Service Provider Obligations</h5>
    <ul>
      <li>Provide true business details, certifications, and pricing.</li>
      <li>Comply with all laws, including service-specific regulations (e.g., licensing for astrologers).</li>
      <li>Respond to User inquiries promptly and professionally.</li>
    </ul>

    <h5>7. Payments & Refunds</h5>
    <ul>
      <li><strong>Booking Fees:</strong> Non-refundable unless otherwise stated.</li>
      <li><strong>Cancellations:</strong> Users may cancel bookings 24+ hours before service; late cancellations forfeit fees.</li>
      <li><strong>Disputes:</strong> Task365 may mediate disputes but is not liable for Service Provider actions.</li>
    </ul>

    <h5>8. Intellectual Property</h5>
    <ul>
      <li>All Platform content (except User/Service Provider submissions) is owned by Task365.</li>
      <li>Users grant Task365 a non-exclusive license to display contributed content (e.g., reviews, images).</li>
    </ul>

    <h5>9. Liability & Disclaimers</h5>
    <ul>
      <li><strong>No Warranty:</strong> Services are provided "as-is." Task365 disclaims warranties for accuracy, availability, or quality.</li>
      <li><strong>Limitation of Liability:</strong> Task365’s liability is capped at the fees paid for the specific service. Excludes indirect/consequential damages.</li>
      <li><strong>Third-Party Links:</strong> Task365 is not responsible for external sites or services linked on the Platform.</li>
    </ul>

    <h5>10. Termination</h5>
    <p>Task365 reserves the right to suspend accounts for breaches, fraud, or unlawful activities. Users may terminate accounts via written notice.</p>

    <h5>11. Dispute Resolution</h5>
    <ul>
      <li><strong>Mediation:</strong> Parties must attempt mediation before arbitration.</li>
      <li><strong>Arbitration:</strong> Disputes resolved under Indian Arbitration Act, 1996, with a sole arbitrator in Bangalore City.</li>
      <li><strong>Jurisdiction:</strong> Courts in Bangalore hold exclusive jurisdiction.</li>
    </ul>

    <h5>12. Amendments</h5>
    <p>Task365 may update these Terms periodically. Continued use after revisions constitutes acceptance.</p>

    <h5>13. Contact</h5>
    <p>For queries, contact:</p>
    <address>
      Lorhan Spot Earn Pvt Ltd<br>
      Email: <a href="mailto:task365.in@gmail.com">task365.in@gmail.com</a><br>
      Address: Flat No. 07/3, Second Floor, 18th Main Jaya Nagar, 9th Block Bangalore, Karnataka – 560041 India
    </address>

    <h5>Annexures</h5>
    <ul>
      <li><a href="#">Privacy Policy</a></li>
      <li><a href="#">Refund Policy</a></li>
      <li><a href="#">IPR Infringement Policy</a></li>
    </ul>

        
    </div>
</div>
<!-- Page Header End !-->


@endsection